#makefile for ArithmeticEquations.cpp
#Author

#This generates the ArithmeticEquations.cpp program
ArithmeticEquations: ArithmeticEquations.cpp
	g++ -o ArithmeticEquations ArithmeticEquations.cpp -std=c++0x

clean:
	rm ArithmeticEquations